
[ids]

*


[main]
capslock = overload(capslock_layer, ~)
rightcontrol = overload(numlocko,numlocko)

[capslock_layer]
h = left
j = down
k = up
l = right
w = C-right
b = C-left
a = home
e = end
c = esc
x = delete
d = backspace
space = enter
z = `
leftshift = `
y = C-c
p = C-v
u = C-z
. = kpdot  

[numlocko]
. = kpdot  
m = kp0  
, = kp0  
j = kp1  
k = kp2  
l = kp3  
u = kp4  
i = kp5  
o = kp6  
7 = kp7  
8 = kp8  
9 = kp9  
p = kpasterisk
; = kpminus
/ = kpplus
0 = kpslash
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
q = f10
w = f11
e = f12
